### ISSUE TITLE
try run it on linux arm

### ISSUE THREAD

**Issue by weigeloveu** [RoyalFlyBy/ChaturbateWatcher#2]
It seem started, but didn't record anything
`
root@localhost:~/chate# ./cw
By (|/)RoyalFlyBy(\|) on GitHub https://github.com/RoyalFlyBy/ChaturbateWatcher
#############################################################################################
Watching 0 streams right now
=============================================================================================
=============================================================================================
#############################################################################################
Watched 0 streams in the past hour
=============================================================================================
=============================================================================================
#############################################################################################
Version 2020.02.25.1release (build:23)
#############################################################################################
`

**Comment by weigeloveu** [comment]
seems a little slow need wait for a while

**Comment by RoyalFlyBy** [comment]
never tried on ARM before

Out of curiosity, what kind of device are you running it on? (In the future I will make a low power machine to save stuff like this program does but for another site.)

**Comment by weigeloveu** [comment]
i tired on my xiaomi 9,used termux,but it doesnt work,and tried ubuntu it worked but when i pressed ctrl c,it will stop recording but the terminal will frozen.
subcribe lots of models,my phone storage cant afford it,hahaha
mybe could use otg hub
