### ISSUE TITLE
Connection in progress forcibly closed by remote host

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/ChaturbateWatcher#3]
Good morning **@RoyalFlyBy**: how are You? I hope safe🤗.
Yesterday, for the first time, I left Your program on for the whole night. In the morning I found _this_ written😵.
```
imap/client: 2020/05/17 23:46:15 error reading response: read tcp 192.168.1.2:49908->52.97.186.98:993: wsarecv: Connessione in corso interrotta forzatamente dall'host remoto.
runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x7d0854, 0xd)
        C:/Go/src/runtime/panic.go:774 +0x79
runtime.sysUsed(0xc66322a000, 0x2000)
        C:/Go/src/runtime/mem_windows.go:83 +0x230
runtime.(*mheap).allocSpanLocked0xa9d8a00x10xaba3e80x11228 +0x203
runtime.(*mheap).alloc_m(0xa9d8a0, 0x1, 0xf, 0xc000450601)
        C:/Go/src/runtime/mheap.go:1022 +0xd0
runtime.(*mheap).alloc.func1()
        C:/Go/src/runtime/mheap.go:1093 +0x53
runtime.systemstack(0x0)
        C:/Go/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
        C:/Go/src/runtime/proc.go:1146

goroutine 52655257 [running]:
runtime.systemstack_switch()
        C:/Go/src/runtime/asm_amd64.s:330 fp=0xc0383c9b08 sp=0xc0383c9b00 pc=0x4593b0
runtime.(*mheap).alloc(0xa9d8a0, 0x1, 0x1000f, 0x0)
        C:/Go/src/runtime/mheap.go:1092 +0x91 fp=0xc0383c9b58 sp=0xc0383c9b08 pc=0x426661
runtime.(*mcentral).grow(0xa9e210, 0x0)
        C:/Go/src/runtime/mcentral.go:255 +0x82 fp=0xc0383c9b98 sp=0xc0383c9b58 pc=0x418192
runtime.(*mcentral).cacheSpan(0xa9e210, 0x6732a6d7)
        C:/Go/src/runtime/mcentral.go:106 +0x305 fp=0xc0383c9bf8 sp=0xc0383c9b98 pc=0x417cb5
0x1c14000xf1380x8c0xc0383c9c180xc0383c9bf80x41773c0x1c14000xf0x20x00x1c14018540x8e0xc0383c9c500xc0383c9c180x40be8e
runtime.mallocgc(0x60, 0x0, 0xc663205101, 0xc6632269c0)
        C:/Go/src/runtime/malloc.go:1022 +0x7d2 fp=0xc0383c9cf0 sp=0xc0383c9c50 pc=0x40c812
runtime.makechan(0x743400, 0x0, 0x3)
950x1a40xc0383c9d380xc0383c9cf00x404f440xc66321e4b0, 0xc663219f80, 0x00x0570xb40xc0383c9e680xc0383c9d380x6e5de40xc66321e4b00xc663219f80, 0xdf8475800, 0x0, 0x0)
92 +0x2b2 fp=0xc0383c9f70 sp=0xc0383c9e68 pc=0x6e6382
email_client/emailclient.(*EClient).InitIdleWithInterval.func1(0xc663226960, 0xc66321e4b0, 0x856fa0, 0xc6632224c0, 0xdf8475800)
        C:/Users/BUNNY/go/src/email_client/emailclient/client.go:1720x500xc0383c9fb80xc0383c9f700x6f084013570x10xc0383c9fc0 sp=0xc0383c9fb80x45b4f1created by email_client/emailclient.(*EClient).InitIdleWithInterval
        C:/Users/BUNNY/go/src/email_client/emailclient/client.go:171 +0x145

goroutine 1 [chan receive, 229 minutes]:
main.main()
        C:/Users/BUNNY/go/src/chaturbate-watcher/main.go:56 +0x5b6

goroutine 19 [syscall, 229 minutes]:
os/signal.signal_recv0x01470xa3230x29290x48
goroutine 68 [select]:
chaturbate-watcher/app.(*MainApp).ListenForEmails(0xc000044680, 0xc00010e1c0, 0xc000019dd0)
        C:/Users/BUNNY/go/src/chaturbate-watcher/app/listener.go:143 +0x665
created by main.main
        C:/Users/BUNNY/go/src/chaturbate-watcher/main.go:51 +0x4f6

goroutine 69 [select]:
chaturbate-watcher/app.(*MainApp).ShowTerminalUI(0xc000044680, 0xc00010e230)
        C:/Users/BUNNY/go/src/chaturbate-watcher/app/tui.go:31 +0x4dc
created by main.main
        C:/Users/BUNNY/go/src/chaturbate-watcher/main.go:52 +0x525

goroutine 70 [select]:
github.com/gosuri/uilive.(*Writer).Listen(0xc000358420)
        C:/Users/BUNNY/go/src/github.com/gosuri/uilive/writer.go:125 +0xaa
created by github.com/gosuri/uilive.(*Writer).Start
        C:/Users/BUNNY/go/src/github.com/gosuri/uilive/writer.go:113 +0x51

goroutine 95 [chan receive, 54 minutes]:
github.com/emersion/go-imap-idle.(*Response).Handle.func1(0xc000372120)
        C:/Users/BUNNY/go/src/github.com/emersion/go-imap-idle/response.go:31 +0x43
created by github.com/emersion/go-imap-idle.(*Response).Handle
        C:/Users/BUNNY/go/src/github.com/emersion/go-imap-idle/response.go:30 +0x83
```
Did the remote email host (**Outlook**) drop the connection? And _why_? I specify that tonight none of the three models I follow has opened the "Room", so there was nothing to register.
Take care Yourself😷.

**Comment by RoyalFlyBy** [comment]
Hi, I'm doing alright, how about you?

About this issue, you said it happened for the first time so I have to ask in order to properly debug:
Has it occurred more times since you reported this?

If it has I may be able to figure out how to fix it, if not it will be a lot harder.
It states an "out of memory" error, so I'm inclined to believe that all the available RAM memory was used and that's why it failed.
IF this happens more often I am pretty sure this is a memory leak bug in the program, nothing dangerous just very inefficient.

**Comment by ghost** [comment]
Thanks for Your kindness, **@RoyalFlyBy**: nobody has contracted Corona here _for now_ (🙏🤞🤘).
The issue I explained to You only occurred three times: I changed PC + OS (Win**7** → Win**10**) and I think it's a bug. I still **don't** master the new OS well🙄: however, when bug happens, I turn off CW, restart it and everything go fine again. 
Of course, if the bug "_strikes_" at night ...

By the way, I'd like to ask You a question.
Thanks to CW I can recorded many Cam Shows of the models I follow from February to nowday, but I would also download the **past** ones. They've been archived on some websites, but all videos are downloadable only through a premium subscription to upstore.net.
Until last year [there was a tool that allowed You to bypass the payment](https://www.youtube.com/watch?v=xj1__ODCf24), but now I **cannot** find it😢. Being a fan of Chaturbate You too, do have any advice, kindly?
Maybe something easy here on GiHub ...

I trust Your experience.

**Comment by RoyalFlyBy** [comment]
For the bug I am going to initially recommend to increase your virtual memory

Guide on how to do it:
https://www.x-plane.com/kb/increasing-virtual-memory-on-windows/

As for the tool to bypass payment on that site, do you still have an older version that used to work in the past? If you could upload it I may be able to reverse engineer it and see how it worked in the first place which in turn will allow me to see if i can fix it.

**Comment by ghost** [comment]
Thanks for Your suggestion and concern, **@RoyalFlyBy**: [the link](https://www.x-plane.com/kb/increasing-virtual-memory-on-windows/) will be very useful to me😊!

As for the tool, I explained myself wrong I never downloaded it; only, through [YouTube video](https://www.youtube.com/watch?v=xj1__ODCf24), YouTube feedbacks, Wayback Machine and rumors on a forum, I know **for sure** that it was downloadable until December 2019 and it worked **perfectly**.

However, since You told me that You're an expert in **reverse engineering**, there's another tool to download videos from a [website](http://camvideos.me/) that stores Cam Shows. I found [this old system](https://drive.google.com/file/d/0B8Ua3jT-LQkBQlRWOXY2dF85cG8/edit) (no virus, I assure) to exceeds limit of 60 seconds ... but there's the activation code problem ...
[**ITS SCREENSAVER**](https://imgur.com/a/uPuaikj).
Maybe it may interest You, I don't know ...
